baseURL: https://caiyun.fun/
languageCode: zh-CN
title: å½©äº‘å½’
#theme: hugo-theme-stack
theme: hugo-theme-stack
defaultContentLanguage: zh-cn
# æ˜¯å¦åŒ…å«ä¸­æ–‡ï¼Œæ—¥è¯­ï¼ŒéŸ©æ–‡
hasCJKLanguage: true
# å¼€å¯æ”¯æŒè¡¨æƒ…ç¬¦å·
# Enable Emoji support
enableEmoji: true
paginate: 5 # éšæ„ç¿»é˜…

params:
  description: "å½©äº‘å½’"
  mainSections: [ "post" ]
  featuredImageField: "featured_image"
  favicon: /favicon.ico
  darkmode: true

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
    avatar:
      enable: true
      src: /rainbow.png
      local: true
    emoji: ğŸŒˆ
    subtitle: å½“æ—¶æ˜æœˆåœ¨ï¼Œæ›¾ç…§å½©äº‘å½’
  article:
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true


menu:
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/Hermes981128
      params:
        icon: brand-github

